
DROP DATABASE IF EXISTS redes_dw;

CREATE DATABASE redes_dw;

USE redes_dw;


CREATE TABLE dim_time (
    TIME_ID DATETIME,
    YEAR_ID INT,
    MONTH_ID INT,
    PRIMARY KEY (TIME_ID)
);

CREATE TABLE dim_location (
	PARISH_CODE VARCHAR(255),
	PARISH_NAME VARCHAR(255),
	MUNICIPALITY_CODE INT,
	MUNICIPALITY_NAME VARCHAR(255),
	DISTRICT_CODE INT,
	DISTRICT_NAME VARCHAR(255),
	PRIMARY KEY (PARISH_CODE)
);

CREATE TABLE dim_voltage (
	LEVEL_CODE INT,
	LEVEL_NAME VARCHAR(255),
	PRIMARY KEY (LEVEL_CODE)
);

CREATE TABLE fact_consumption (
    CONSUMPTIONNUMBER INT,
	ENERGYCONSUMPTION DOUBLE,
	TIME_ID DATETIME,
	PARISH_CODE VARCHAR(255),
	LEVEL_CODE INT,
	PRIMARY KEY (CONSUMPTIONNUMBER),
    FOREIGN KEY (TIME_ID) REFERENCES dim_time (TIME_ID),
    FOREIGN KEY (PARISH_CODE) REFERENCES dim_location (PARISH_CODE),
    FOREIGN KEY (LEVEL_CODE) REFERENCES dim_voltage (LEVEL_CODE)
);
