
drop table if exists fact_consumption;
drop table if exists dim_time;
drop table if exists dim_location;
drop table if exists dim_voltage;

CREATE TABLE dim_time (
    TIME_ID INT AUTO_INCREMENT,
    DATE_ID DATETIME,
    YEAR_ID INT,
    MONTH_ID INT,
    MONTH_NAME VARCHAR(255),
    PRIMARY KEY (TIME_ID)
);

CREATE TABLE dim_location (
	LOCATION_ID INT AUTO_INCREMENT,
	PARISH_CODE VARCHAR(255),
	PARISH_NAME VARCHAR(255),
	MUNICIPALITY_CODE INT,
	MUNICIPALITY_NAME VARCHAR(255),
	DISTRICT_CODE INT,
	DISTRICT_NAME VARCHAR(255),
	PRIMARY KEY (LOCATION_ID)
);

CREATE TABLE dim_voltage (
	VOLTAGE_ID INT AUTO_INCREMENT,
	VOLTAGE_NAME VARCHAR(255),
	PRIMARY KEY (VOLTAGE_ID)
);

CREATE TABLE fact_consumption (
    CONSUMPTIONNUMBER INT AUTO_INCREMENT	,
	ENERGYCONSUMPTION DOUBLE,
	TIME_ID INT,
	LOCATION_ID INT,
	VOLTAGE_ID INT,
	PRIMARY KEY (CONSUMPTIONNUMBER),
    FOREIGN KEY (TIME_ID) REFERENCES dim_time (TIME_ID),
    FOREIGN KEY (LOCATION_ID) REFERENCES dim_location (LOCATION_ID),
    FOREIGN KEY (VOLTAGE_ID) REFERENCES dim_voltage (VOLTAGE_ID)
);
