drop table if exists fact_consumption;
drop table if exists dim_voltage;

CREATE TABLE dim_voltage (
	LEVEL_CODE INT AUTO_INCREMENT,
	LEVEL_NAME VARCHAR(255),
	PRIMARY KEY (LEVEL_CODE)
);

CREATE TABLE fact_consumption (
    CONSUMPTIONNUMBER INT,
	ENERGYCONSUMPTION DOUBLE,
	TIME_ID DATETIME,
	PARISH_CODE VARCHAR(255),
	LEVEL_CODE INT,
	PRIMARY KEY (CONSUMPTIONNUMBER),
    FOREIGN KEY (TIME_ID) REFERENCES dim_time (TIME_ID),
    FOREIGN KEY (PARISH_CODE) REFERENCES dim_location (PARISH_CODE),
    FOREIGN KEY (LEVEL_CODE) REFERENCES dim_voltage (LEVEL_CODE)
);
