drop table if exists fact_consumption;

CREATE TABLE fact_consumption (
	ENERGYCONSUMPTION DOUBLE,
	TIME_ID DATETIME,
	PARISH_CODE VARCHAR(255),
	LEVEL_NAME VARCHAR(255),
	PRIMARY KEY (TIME_ID, PARISH_CODE),
    FOREIGN KEY (TIME_ID) REFERENCES dim_time (TIME_ID),
    FOREIGN KEY (PARISH_CODE) REFERENCES dim_location (PARISH_CODE),
    FOREIGN KEY (LEVEL_NAME) REFERENCES dim_voltage (LEVEL_NAME)
);
