drop table if exists fact_consumption;

CREATE TABLE fact_consumption (
    CONSUMPTIONNUMBER INT AUTO_INCREMENT	,
	ENERGYCONSUMPTION DOUBLE,
	TIME_ID INT,
	LOCATION_ID INT,
	VOLTAGE_ID INT,
	PRIMARY KEY (CONSUMPTIONNUMBER),
    FOREIGN KEY (TIME_ID) REFERENCES dim_time (TIME_ID),
    FOREIGN KEY (LOCATION_ID) REFERENCES dim_location (LOCATION_ID),
    FOREIGN KEY (VOLTAGE_ID) REFERENCES dim_voltage (VOLTAGE_ID)
);
